- include_tasks: all-unix.yml
  when: ansible_system == "Linux" or ansible_system == "FreeBSD"
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"
- include_tasks: freebsd.yml
  when: ansible_os_family == "FreeBSD"
- include_tasks: config-and-issue.yml
  when: ansible_system == "Linux" or ansible_system == "FreeBSD"