---

- name: Create directory /etc/letsencrypt
  ansible.builtin.file:
    path: "/etc/letsencrypt"
    state: directory
    mode: 0700

- name: Write SA key
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    mode: 0600
    owner: root
    group: root
  loop:
    - { src: "/Users/ronnyforberger/google-secrets/production-300716-80cecefe51f0.json", dest: "/etc/letsencrypt/production-300716-80cecefe51f0.json"}

- name: Install certbot
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-certbot-dns-google
    - certbot

- name: Create cronjob
  ansible.builtin.cron:
    name: "letsencrypt_{{ item.hostname }}"
    backup: yes
    day: "*"
    hour: "2"
    minute: "{{ item.minute }}"
    month: "*"
    weekday: "*"
    user: "root"
    job: "{{ item.command }}"
  loop: "{{ letsencrypt.cron.jobs }}"

- name: Issue cert for the first time
  ansible.builtin.command:
    cmd: "{{ item.command }}"
    creates: "/etc/letsencrypt/live/{{ item.hostname }}/fullchain.pem"
  loop: "{{ letsencrypt.cron.jobs }}"



